import L from "leaflet";
// generated by tools/map-pipeline/render.mjs (npm run map:build) — always in
// sync with public/omap.png; was hardcoded before, which kept the OLD extent
// after the base map changed (2026-07-12)
import bounds from "./omap-bounds.json";

// Georeferenced O-map raster (rendered from the .omap; served from /public).
export const OMAP_BOUNDS = {
  north: bounds.north,
  south: bounds.south,
  west: bounds.west,
  east: bounds.east,
};

/**
 * Set up base layers on a Leaflet map: OSM streets + the orienteering map as
 * an overlay, with a layer switch. Centres on the O-map. Returns the map.
 * The O-map is what you need to place controls accurately (OSM lacks the
 * vegetation/rock/path detail).
 */
export function setupBaseMap(elId: string): L.Map {
  const b = OMAP_BOUNDS;
  const map = L.map(elId, { zoomControl: true });

  const osm = L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
    maxZoom: 20,
    attribution: "© OpenStreetMap",
  });
  const omap = L.imageOverlay(
    "/omap.png",
    [
      [b.south, b.west],
      [b.north, b.east],
    ],
    { opacity: 1 },
  );

  osm.addTo(map);
  omap.addTo(map);
  L.control.layers(
    { OSM: osm },
    { "Orienteering map": omap },
    { collapsed: false },
  ).addTo(map);

  map.fitBounds([
    [b.south, b.west],
    [b.north, b.east],
  ]);
  return map;
}
